#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-stax2-api
Version  : 3.1.4
Release  : 1
URL      : https://github.com/FasterXML/stax2-api/archive/stax2-api-3.1.4.tar.gz
Source0  : https://github.com/FasterXML/stax2-api/archive/stax2-api-3.1.4.tar.gz
Source1  : https://repo1.maven.org/maven2/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.jar
Source2  : https://repo1.maven.org/maven2/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: mvn-stax2-api-data = %{version}-%{release}

%description
# Overview
Stax2 API is an extension to standard [Stax](http://en.wikipedia.org/wiki/StAX) API ("STandard Api for Xml procesing"),
pull-parser API of JDK, added in JDK 6.

%package data
Summary: data components for the mvn-stax2-api package.
Group: Data

%description data
data components for the mvn-stax2-api package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/woodstox/stax2-api/3.1.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/woodstox/stax2-api/3.1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/woodstox/stax2-api/3.1.4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/woodstox/stax2-api/3.1.4


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.jar
/usr/share/java/.m2/repository/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.pom
